fixing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,10 +92,19 @@ jobs:
       - name: Trigger Render Deploy
         run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
       
-      - name: Wait for deployment
-        run: sleep 40
-
       - name: Health Check
-        run: curl -f https://e-commerce-with-postgre-and-prisma-4.onrender.com/health || exit 1
+        run: |
+          for i in {1..6}; do
+            echo "Checking health..."
+            if curl -f https://e-commerce-with-postgre-and-prisma-4.onrender.com/health; then
+              echo "App is healthy "
+              exit 0
+            fi
+            echo "Waiting for app to be ready..."
+            sleep 15
+          done
+          echo "Health Check Failed"
+          exit 1
+           
     
     timeout-minutes: 10
